import Vue from "vue";
import {
    Button,
    Menu,
    Submenu,
    MenuItem,
    MenuItemGroup,
    Form,
    FormItem,
    Input,
    RadioGroup,
    RadioButton,
    Container,
    Aside,
    Header,
    Footer,
    Main,
    Select,
    Option,
    Loading,
    Alert,
    Breadcrumb,
    BreadcrumbItem,
    DropdownMenu,
    DropdownItem,
    Dropdown,
    Avatar,
    Table,
    TableColumn,
    Popover,
    Tag,
    Row,
    Card,
    Col,
    Dialog,
    Steps,
    Step,
    Transfer,

} from "element-ui";
import "element-ui/lib/theme-chalk/index.css";

Vue.use(Transfer);
Vue.use(Step);
Vue.use(Steps);
Vue.use(Dialog);
Vue.use(Col);
Vue.use(Card);
Vue.use(Row);
Vue.use(Tag);
Vue.use(Popover);
Vue.use(TableColumn);
Vue.use(Table);
Vue.use(DropdownMenu);
Vue.use(DropdownItem);
Vue.use(Dropdown);
Vue.use(Avatar);
Vue.use(BreadcrumbItem);
Vue.use(Breadcrumb);
Vue.use(Alert);
Vue.use(Loading);
Vue.use(Option);
Vue.use(Select);
Vue.use(Button);
Vue.use(Menu);
Vue.use(Submenu);
Vue.use(MenuItem);
Vue.use(MenuItemGroup);
Vue.use(Form);
Vue.use(FormItem);
Vue.use(Input);
Vue.use(RadioGroup);
Vue.use(RadioButton);
Vue.use(Container);
Vue.use(Footer);
Vue.use(Header);
Vue.use(Main);
Vue.use(Aside);
