
spring:
  datasource:
    url: jdbc:mysql://localhost/tms_dev?serverTimezone=GMT
    username: tms
    password: m4a1421
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 2048MB
server:
  port: 80


